# Generated by Django 2.0.3 on 2019-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_text',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_text',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
